### ISSUE TITLE
Plugin not showing up on 2.6.4 (build 1286)

### ISSUE THREAD

**Issue by kalapi** [jenskutilek/RedArrow-Glyphs#28]
Hello Jens, 

Hope you're well :) 

For some reason the plugin doesn't show up in Glyphs. I've tried installing it manually from releases, as well as from the Plugin Manager. It's possible that I might be doing something wrong, but I don't know what. 

I'm on macOS 10.15.5

Best,
Kalapi

**Comment by schriftgestalt** [comment]
Installing it manually on 10.15 doesn’t work in Glyphs 2.6.4. The notarization is causing problems. That is fixed in 2.6.5-1342.

I had a look at the code and simplified it a bit. Can you try again? It should run on 2.6.4 and 2.6.5 now.

**Comment by kalapi** [comment]
Hi @schriftgestalt,

Still doesn't work for me. Tried installing both ways, and made sure to remove it from both–`Plugins` and `Repositories` directories before re-installing.

**Comment by schriftgestalt** [comment]
What exactly happens? Any error message in the macro window?

**Comment by kalapi** [comment]
Nothing at all. It installs fine but doesn't show up in either the `View` menu or on the Reporter Toggler plugin i'm using

**Comment by kalapi** [comment]
![Screenshot 2020-07-08 at 2 20 32 AM](https://user-images.githubusercontent.com/15804460/86841489-873f0080-c093-11ea-84a5-1d56ccba0650.png)

**Comment by schriftgestalt** [comment]
Stupid question. You restarted Glyphs after installing?

**Comment by kalapi** [comment]
Yes, multiple times :)

**Comment by jenskutilek** [comment]
Thanks, @schriftgestalt, for your updates!

I don't have macOS 10.15, so I'm not sure how to debug this ...

**Comment by schriftgestalt** [comment]
I don’t think it is related to the version of MacOS. I just tried and it works fine for me.

**Comment by kmohl** [comment]
Exactly the same issue here. Plugin installed, but no show. Glyphs 2.6.5, MacOS 10.15.6.

**Comment by schriftgestalt** [comment]
It works fine for me in version 2.6.4, 2.6.5 and 2.6.6. (macOS 10.15.6)
Can you check the Plugin folder if it installed correctly

**Comment by jenskutilek** [comment]
This is just a guess, but could you check contents of the plugin bundle (right-click on `RedArrow.glyphsReporter`, "Show Package Contents") and remove any `.pyc` files and `__pycache__` folders that might be in there? Perhaps some code is imported from an old version of a compiled Python file.

**Comment by kmohl** [comment]
1. @schriftgestalt this is the plugin install path: Library > Application Support > Glyphs > Repositories > Red Arrow
2. @jenskutilek I removed all .pyc files (no __pycache__ files found), but the plugin still doesn't show up in the View menu. Tried installing/reinstalling both through Plugin Manager and manually, but to no avail.

**Comment by yurlick** [comment]
I have the same problem. After intallation of Red Arrows in Macro panel I see these errors
![Снимок экрана 2020-08-07 в 13 01 24](https://user-images.githubusercontent.com/47480585/89634581-4ca4cf80-d8ae-11ea-894b-59e3c7c513fd.png)

**Comment by schriftgestalt** [comment]
Can you update the modules in Preferences > Addons > Modules?

**Comment by kalapi** [comment]
Works for me after re-installing the modules. I also updated Glyphs to 2.6.5 (1342).
